### ISSUE TITLE
Array access at offset -1 underflows this variable: 'template'.

### ISSUE THREAD

**Issue by sergio-nsk** [bratizgut/labs#3]
https://github.com/bratizgut/labs/blob/0451c67e9b364d2d86875789080250a828608bdd/lab1.c#L28

На первом тесте получилось j < 0, и обращение к элементу массива template по отрицательному индексу. Программа падает.

**Comment by bratizgut** [comment]
Не могу  воспроизвести ошибку

**Comment by sergio-nsk** [comment]
Смотри внимательнее.  У тебя сначала идёт обращение к элементу `pattern[j]` при j=-1, а потом проверка `(j>=0)`. Это проходили: точки следования.
